name: Compilar WhisperDesktop

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar Codigo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Instalar C++ ATL via Chocolatey
      run: choco install visualstudio2022-component-vc-atl -y

    - name: Configurar Ambiente MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Configurar NuGet
      uses: nuget/setup-nuget@v2

    - name: Restaurar Pacotes
      run: nuget restore Examples\WhisperDesktop\WhisperDesktop.vcxproj

    - name: Compilar WhisperDesktop
      run: msbuild Examples\WhisperDesktop\WhisperDesktop.vcxproj /p:Configuration=Release /p:Platform="x64"

    - name: Salvar Executavel
      uses: actions/upload-artifact@v4
      with:
        name: WhisperDesktop-Pronto
        path: |
          **/x64/Release/**/*
          **/Release/**/*
